language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - composer install
  - echo "elasticroute_api_key=$API_KEY" >> tests/.env
  - echo "elasticroute_path=$ER_PATH" >> tests/.env
  - cat tests/.env.example >> tests/.env
script:
  - vendor/phpunit/phpunit/phpunit tests --bootstrap tests/bootstrap.php