language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - composer install
  – cp tests/.env.example tests/.env
  - echo "elasticroute_api_key=$API_KEY" >> tests/.env
script:
  - phpunit tests --bootstrap tests/bootstrap.php